<?php include "./header.php"; ?>
<html>
    <head>
        <link rel="stylesheet" href="./css/services.css">
    </head>
<body>

    <section>
	    <div class="simg"><img src="./image/taxation.png"></div>	
	</section>


    <br><br>
    <div class="eqcenten">
        <img src="./image/services/taxation/t2.jpg" ali=""  />
    </div><br><br>
    
    <h2 >What is Taxation ?</h2>
    
    <p class="eqfont">
        Taxation is a term for when a taxing authority, usually a government, levies or imposes 
        a financial obligation on its citizens or residents. Paying taxes to governments or 
        officials has been a mainstay of civilization since ancient times.
            <br><br>
        The term "taxation" applies to all types of involuntary levies, from income to capital 
        gains to estate taxes. Though taxation can be a noun or verb, it is usually referred to 
        as an act; the resulting revenue is usually called "taxes." 
    </p>

    <h2>Understanding Taxation  </h2>

    <p class="eqfont">
        Taxation is differentiated from other forms of payment, such as market exchanges, 
        in that taxation does not require consent and is not directly tied to any services
        rendered. The government compels taxation through an implicit or explicit threat 
        of force. Taxation is legally different than extortion or a protection racket because
        the imposing institution is a government, not private actors. 
            <br><br><br>
    </p>

              
    <p class="eqfont2">
        Tax systems have varied considerably across jurisdictions and time. In most modern 
        systems, taxation occurs on both physical assets, such as property and specific events,
         such as a sales transaction. The formulation of tax policies is one of the most 
         critical and contentious issues in modern politics. 
    </p>

    <div class="eqcenten2">
        <img src="./image/services/taxation/t1.png" ali=""  />
    </div>

    <h2>Different Types of Taxation </h2>
    <p class="eqfont2"><b>Income tax:</b> Governments impose income taxes on financial income 
        generated by all entities within their jurisdiction, including individuals and businesses.
        <br><br>
        <b>Corporate tax:</b> This type of tax is imposed on the profit of a business.
        <br><br>
        <b>Capital gains:</b> A tax on capital gains is imposed on any capital gains or 
        profits made by people or businesses from the sale of certain assets including stocks, bonds, or real estate.
        <br><br>
        <b>Property tax:</b> A property tax is asses by a local government and paid for by the owner of a property. 
        This tax is calculated based on property and land values. 
        <br><br>
        <b>Inheritance:</b> A type of tax levied on individuals who inherit the estate of a deceased person. 
        <br><br>
        <b>Sales tax:</b> A consumption tax imposed by a government on the sale of goods and services. 
            This can take the form of a value-added tax (VAT), a goods and services tax (GST), a state or provincial sales tax, or an excise tax. 
    </p>
  
    <br><br>
    <video controls>
<source src="./image/video/tax.mp4" type="video/mp4">
</video> 
    <?php include "./footer.php";?>
</body>
</html>